library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity bram_conv3x3_weight is
    port(
        clk   : in  std_logic;                          -- clock
        en    : in  std_logic;                          -- read enable
        addr  : in  std_logic_vector(11 downto 0);      -- dia chi doc (0..2303)
        dout  : out std_logic_vector(15 downto 0)       -- gia tri Q8.8
    );
end entity bram_conv3x3_weight;

architecture rtl of bram_conv3x3_weight is

    type rom_type is array (0 to 2303) of std_logic_vector(15 downto 0);

    constant ROM : rom_type := (
        -- oc=0, ic=0
        x"FFFB", x"FFFC", x"FFFC", x"FFFB", x"FFFA", x"FFFD", x"FFFC", x"FFFE",
        x"FFFE",
        -- oc=0, ic=1
        x"FFFF", x"FFFF", x"0000", x"FFFF", x"FFFF", x"0002", x"FFFE", x"FFFF",
        x"FFFF",
        -- oc=0, ic=2
        x"FFF7", x"FFF9", x"FFF8", x"FFF9", x"FFFA", x"FFFB", x"FFF8", x"FFFB",
        x"FFF9",
        -- oc=0, ic=3
        x"FFF3", x"FFF3", x"FFF5", x"FFF6", x"FFF3", x"FFFA", x"FFF4", x"FFF7",
        x"FFF6",
        -- oc=0, ic=4
        x"FFF8", x"FFF8", x"FFF9", x"FFF9", x"FFF7", x"FFFD", x"FFF7", x"FFFC",
        x"FFFA",
        -- oc=0, ic=5
        x"FFF6", x"FFF6", x"FFF7", x"FFF7", x"FFF4", x"FFFD", x"FFF4", x"FFF7",
        x"FFF8",
        -- oc=0, ic=6
        x"FFF7", x"FFF9", x"FFF8", x"FFF8", x"FFF9", x"FFFB", x"FFF7", x"FFFB",
        x"FFF9",
        -- oc=0, ic=7
        x"FFF3", x"FFF3", x"FFF7", x"FFF6", x"FFF4", x"FFF9", x"FFF6", x"FFF8",
        x"FFF7",
        -- oc=0, ic=8
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0001", x"FFFF", x"0001",
        x"0001",
        -- oc=0, ic=9
        x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"FFFF", x"FFFE", x"0000",
        x"0000",
        -- oc=0, ic=10
        x"0000", x"0001", x"0001", x"0000", x"0000", x"0001", x"0000", x"0001",
        x"0000",
        -- oc=0, ic=11
        x"FFFB", x"FFFC", x"FFFD", x"FFFC", x"FFFB", x"FFFD", x"FFFD", x"FFFE",
        x"FFFD",
        -- oc=0, ic=12
        x"FFFB", x"FFFC", x"FFFC", x"FFFD", x"FFFD", x"FFFF", x"FFFB", x"FFFD",
        x"FFFD",
        -- oc=0, ic=13
        x"FFFB", x"FFFD", x"FFFC", x"FFFE", x"FFFE", x"0000", x"FFFD", x"FFFE",
        x"FFFD",
        -- oc=0, ic=14
        x"FFF6", x"FFF6", x"FFF8", x"FFF7", x"FFF7", x"FFFA", x"FFF5", x"FFF6",
        x"FFF6",
        -- oc=0, ic=15
        x"FFFB", x"FFFB", x"FFFB", x"FFFC", x"FFFA", x"FFFD", x"FFFC", x"FFFE",
        x"FFFC",
        -- oc=1 (144 values)
        x"FFFC", x"FFFD", x"FFFD", x"FFFC", x"FFFC", x"FFFE", x"FFFD", x"FFFF",
        x"FFFF", x"FFFE", x"FFFE", x"FFFF", x"FFFE", x"FFFE", x"0000", x"FFFD",
        x"FFFE", x"FFFE", x"FFF8", x"FFFA", x"FFF8", x"FFFA", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFFA", x"FFF4", x"FFF4", x"FFF5", x"FFF7", x"FFF4",
        x"FFFA", x"FFF5", x"FFF8", x"FFF7", x"FFF8", x"FFF8", x"FFF9", x"FFF9",
        x"FFF7", x"FFFD", x"FFF7", x"FFFC", x"FFFA", x"FFF7", x"FFF6", x"FFF8",
        x"FFF8", x"FFF4", x"FFFD", x"FFF5", x"FFF8", x"FFF9", x"FFF7", x"FFF9",
        x"FFF9", x"FFF9", x"FFF9", x"FFFB", x"FFF8", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF7", x"FFF6", x"FFF4", x"FFF9", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0001", x"FFFF", x"0000",
        x"0000", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"FFFF", x"FFFE",
        x"0000", x"0000", x"FFFF", x"0000", x"0000", x"FFFF", x"FFFF", x"0000",
        x"FFFF", x"0000", x"FFFF", x"FFFC", x"FFFD", x"FFFE", x"FFFC", x"FFFC",
        x"FFFE", x"FFFE", x"FFFE", x"FFFE", x"FFFB", x"FFFC", x"FFFC", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFA", x"FFFC", x"FFFC",
        x"FFFD", x"FFFD", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFF7", x"FFF7",
        x"FFF8", x"FFF8", x"FFF8", x"FFFB", x"FFF6", x"FFF7", x"FFF6", x"FFFB",
        x"FFFB", x"FFFB", x"FFFC", x"FFFB", x"FFFD", x"FFFD", x"FFFE", x"FFFD",
        -- oc=2 (144 values)
        x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFB", x"FFFE", x"FFFC", x"FFFF",
        x"FFFE", x"FFFE", x"FFFF", x"FFFF", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF7", x"FFF9", x"FFF8", x"FFF9", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFF9", x"FFF4", x"FFF3", x"FFF5", x"FFF7", x"FFF4",
        x"FFFA", x"FFF5", x"FFF7", x"FFF7", x"FFF8", x"FFF8", x"FFF9", x"FFF9",
        x"FFF7", x"FFFE", x"FFF7", x"FFFC", x"FFFA", x"FFF6", x"FFF6", x"FFF8",
        x"FFF8", x"FFF4", x"FFFD", x"FFF5", x"FFF8", x"FFF9", x"FFF7", x"FFF9",
        x"FFF8", x"FFF8", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF7", x"FFF6", x"FFF4", x"FFF9", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0001", x"FFFF", x"0001",
        x"0001", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"FFFF", x"FFFE",
        x"0000", x"0000", x"FFFF", x"0000", x"0000", x"0000", x"FFFF", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFC",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFB", x"FFFC", x"FFFC", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFB", x"FFFC", x"FFFC",
        x"FFFD", x"FFFE", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFF6", x"FFF7",
        x"FFF8", x"FFF8", x"FFF7", x"FFFA", x"FFF6", x"FFF7", x"FFF6", x"FFFB",
        x"FFFB", x"FFFB", x"FFFC", x"FFFA", x"FFFD", x"FFFD", x"FFFE", x"FFFC",
        -- oc=3 (144 values)
        x"FFFB", x"FFFC", x"FFFC", x"FFFB", x"FFFB", x"FFFE", x"FFFC", x"FFFE",
        x"FFFE", x"FFFE", x"FFFF", x"0000", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF7", x"FFF9", x"FFF8", x"FFF9", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFF9", x"FFF3", x"FFF2", x"FFF4", x"FFF6", x"FFF3",
        x"FFF9", x"FFF4", x"FFF6", x"FFF6", x"FFF8", x"FFF7", x"FFF9", x"FFF8",
        x"FFF7", x"FFFD", x"FFF6", x"FFFB", x"FFF9", x"FFF6", x"FFF6", x"FFF7",
        x"FFF7", x"FFF4", x"FFFD", x"FFF4", x"FFF7", x"FFF8", x"FFF7", x"FFF9",
        x"FFF8", x"FFF8", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF7", x"FFF6", x"FFF4", x"FFF9", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0001", x"FFFF", x"0001",
        x"0001", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"0000", x"FFFE",
        x"0000", x"0000", x"0000", x"0000", x"0000", x"0000", x"0000", x"0001",
        x"0000", x"0000", x"0000", x"FFFB", x"FFFC", x"FFFD", x"FFFC", x"FFFB",
        x"FFFD", x"FFFD", x"FFFE", x"FFFD", x"FFFB", x"FFFC", x"FFFD", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFE", x"FFFD", x"FFFB", x"FFFD", x"FFFC",
        x"FFFD", x"FFFE", x"FFFF", x"FFFD", x"FFFE", x"FFFD", x"FFF6", x"FFF7",
        x"FFF8", x"FFF8", x"FFF7", x"FFFA", x"FFF5", x"FFF7", x"FFF6", x"FFFB",
        x"FFFB", x"FFFB", x"FFFC", x"FFFA", x"FFFD", x"FFFD", x"FFFE", x"FFFD",
        -- oc=4 (144 values)
        x"FFFB", x"FFFC", x"FFFC", x"FFFB", x"FFFB", x"FFFE", x"FFFC", x"FFFE",
        x"FFFE", x"FFFE", x"FFFF", x"0000", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF7", x"FFF9", x"FFF8", x"FFF9", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFF9", x"FFF3", x"FFF3", x"FFF4", x"FFF6", x"FFF3",
        x"FFF9", x"FFF4", x"FFF6", x"FFF6", x"FFF7", x"FFF7", x"FFF8", x"FFF8",
        x"FFF6", x"FFFD", x"FFF6", x"FFFB", x"FFF9", x"FFF6", x"FFF6", x"FFF7",
        x"FFF7", x"FFF3", x"FFFC", x"FFF4", x"FFF7", x"FFF8", x"FFF7", x"FFF8",
        x"FFF8", x"FFF8", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFF9", x"FFF3",
        x"FFF3", x"FFF6", x"FFF6", x"FFF4", x"FFF8", x"FFF6", x"FFF8", x"FFF6",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0001", x"FFFF", x"0001",
        x"0001", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"0000", x"FFFE",
        x"0000", x"0000", x"0000", x"0000", x"0000", x"0000", x"0000", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFC", x"FFFD", x"FFFC", x"FFFB",
        x"FFFD", x"FFFD", x"FFFE", x"FFFD", x"FFFB", x"FFFC", x"FFFC", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFB", x"FFFC", x"FFFC",
        x"FFFD", x"FFFD", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFF6", x"FFF6",
        x"FFF7", x"FFF7", x"FFF7", x"FFFA", x"FFF5", x"FFF6", x"FFF5", x"FFFB",
        x"FFFB", x"FFFB", x"FFFC", x"FFFA", x"FFFD", x"FFFC", x"FFFE", x"FFFC",
        -- oc=5 (144 values)
        x"FFFB", x"FFFC", x"FFFD", x"FFFC", x"FFFB", x"FFFE", x"FFFC", x"FFFF",
        x"FFFE", x"FFFE", x"FFFF", x"FFFF", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF8", x"FFF9", x"FFF8", x"FFFA", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFF9", x"FFF4", x"FFF3", x"FFF5", x"FFF7", x"FFF4",
        x"FFFA", x"FFF5", x"FFF7", x"FFF7", x"FFF8", x"FFF8", x"FFF9", x"FFF9",
        x"FFF7", x"FFFE", x"FFF7", x"FFFC", x"FFFA", x"FFF5", x"FFF5", x"FFF7",
        x"FFF7", x"FFF3", x"FFFC", x"FFF4", x"FFF7", x"FFF8", x"FFF7", x"FFF9",
        x"FFF9", x"FFF9", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF7", x"FFF6", x"FFF5", x"FFF9", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0001", x"FFFF", x"0001",
        x"0001", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"0000", x"FFFE",
        x"0000", x"0000", x"FFFF", x"0000", x"0000", x"0000", x"FFFF", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFC",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFB", x"FFFC", x"FFFC", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFB", x"FFFD", x"FFFC",
        x"FFFD", x"FFFE", x"FFFF", x"FFFD", x"FFFE", x"FFFD", x"FFF6", x"FFF7",
        x"FFF8", x"FFF8", x"FFF7", x"FFFA", x"FFF5", x"FFF7", x"FFF6", x"FFFB",
        x"FFFC", x"FFFB", x"FFFC", x"FFFB", x"FFFE", x"FFFD", x"FFFE", x"FFFD",
        -- oc=6 (144 values)
        x"0015", x"0016", x"0015", x"0017", x"0018", x"0017", x"0016", x"0017",
        x"0016", x"000F", x"000F", x"000F", x"0010", x"0010", x"0010", x"0010",
        x"0010", x"0010", x"001B", x"001D", x"001C", x"001D", x"001F", x"001F",
        x"001C", x"001F", x"001E", x"0037", x"003A", x"0038", x"003C", x"003F",
        x"003E", x"0039", x"003D", x"003B", x"0024", x"0026", x"0024", x"0027",
        x"0028", x"0028", x"0025", x"0027", x"0026", x"002A", x"002B", x"002A",
        x"002C", x"002E", x"002D", x"002B", x"002D", x"002B", x"0013", x"0014",
        x"0013", x"0014", x"0014", x"0014", x"0013", x"0014", x"0013", x"0023",
        x"0025", x"0023", x"0027", x"0029", x"0028", x"0026", x"0028", x"0026",
        x"0012", x"0013", x"0013", x"0014", x"0014", x"0014", x"0014", x"0014",
        x"0014", x"0025", x"0027", x"0025", x"0027", x"0029", x"0028", x"0026",
        x"0028", x"0027", x"0006", x"0006", x"0005", x"0006", x"0006", x"0006",
        x"0006", x"0006", x"0006", x"0010", x"0011", x"0011", x"0012", x"0012",
        x"0012", x"0012", x"0013", x"0012", x"000D", x"000E", x"000E", x"000E",
        x"000F", x"000F", x"000E", x"000F", x"000E", x"000D", x"000E", x"000E",
        x"000F", x"0010", x"000F", x"000E", x"000F", x"000F", x"001A", x"001C",
        x"001A", x"001D", x"001F", x"001E", x"001B", x"001D", x"001B", x"001D",
        x"001E", x"001D", x"001F", x"0020", x"001F", x"001E", x"001F", x"001E",
        -- oc=7 (144 values)
        x"FFFB", x"FFFC", x"FFFC", x"FFFB", x"FFFA", x"FFFD", x"FFFC", x"FFFE",
        x"FFFE", x"FFFE", x"FFFF", x"0000", x"FFFF", x"FFFE", x"0002", x"FFFE",
        x"FFFF", x"FFFF", x"FFF7", x"FFF9", x"FFF7", x"FFF9", x"FFFA", x"FFFB",
        x"FFF7", x"FFFB", x"FFF9", x"FFF3", x"FFF3", x"FFF4", x"FFF6", x"FFF3",
        x"FFFA", x"FFF4", x"FFF7", x"FFF6", x"FFF8", x"FFF8", x"FFF9", x"FFF9",
        x"FFF7", x"FFFE", x"FFF7", x"FFFC", x"FFFA", x"FFF6", x"FFF6", x"FFF7",
        x"FFF7", x"FFF3", x"FFFC", x"FFF4", x"FFF7", x"FFF8", x"FFF6", x"FFF8",
        x"FFF7", x"FFF8", x"FFF8", x"FFFA", x"FFF6", x"FFFA", x"FFF9", x"FFF1",
        x"FFF1", x"FFF5", x"FFF5", x"FFF3", x"FFF7", x"FFF4", x"FFF7", x"FFF5",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFD", x"0001", x"FFFF", x"0001",
        x"0001", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"0000", x"FFFE",
        x"0000", x"0000", x"0000", x"0000", x"0000", x"0000", x"0000", x"0001",
        x"0000", x"0001", x"0000", x"FFFB", x"FFFC", x"FFFD", x"FFFB", x"FFFB",
        x"FFFD", x"FFFD", x"FFFD", x"FFFD", x"FFFB", x"FFFB", x"FFFC", x"FFFC",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFB", x"FFFD", x"FFFC",
        x"FFFD", x"FFFE", x"FFFF", x"FFFD", x"FFFE", x"FFFD", x"FFF5", x"FFF6",
        x"FFF7", x"FFF7", x"FFF6", x"FFFA", x"FFF5", x"FFF6", x"FFF5", x"FFFB",
        x"FFFB", x"FFFB", x"FFFC", x"FFFA", x"FFFE", x"FFFD", x"FFFE", x"FFFC",
        -- oc=8 (144 values)
        x"FFFB", x"FFFC", x"FFFD", x"FFFC", x"FFFB", x"FFFE", x"FFFC", x"FFFF",
        x"FFFE", x"FFFE", x"FFFF", x"FFFF", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF7", x"FFF9", x"FFF8", x"FFF9", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFF9", x"FFF3", x"FFF3", x"FFF5", x"FFF6", x"FFF3",
        x"FFFA", x"FFF5", x"FFF7", x"FFF7", x"FFF8", x"FFF8", x"FFF9", x"FFF8",
        x"FFF7", x"FFFD", x"FFF6", x"FFFB", x"FFF9", x"FFF6", x"FFF6", x"FFF7",
        x"FFF7", x"FFF4", x"FFFC", x"FFF4", x"FFF7", x"FFF8", x"FFF7", x"FFF9",
        x"FFF9", x"FFF9", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF7", x"FFF6", x"FFF5", x"FFF9", x"FFF6", x"FFF9", x"FFF7",
        x"FFFC", x"FFFD", x"FFFD", x"FFFD", x"FFFC", x"0000", x"FFFE", x"0000",
        x"0000", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"FFFF", x"FFFE",
        x"0000", x"0000", x"0000", x"0000", x"0000", x"0000", x"0000", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFC", x"FFFD", x"FFFC", x"FFFC",
        x"FFFD", x"FFFD", x"FFFE", x"FFFE", x"FFFB", x"FFFC", x"FFFC", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFB", x"FFFC", x"FFFC",
        x"FFFD", x"FFFE", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFF6", x"FFF7",
        x"FFF8", x"FFF8", x"FFF7", x"FFFA", x"FFF6", x"FFF7", x"FFF6", x"FFFB",
        x"FFFB", x"FFFB", x"FFFC", x"FFFA", x"FFFD", x"FFFC", x"FFFE", x"FFFC",
        -- oc=9 (144 values)
        x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFB", x"FFFE", x"FFFC", x"FFFF",
        x"FFFE", x"FFFE", x"FFFF", x"FFFF", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF8", x"FFFA", x"FFF8", x"FFFA", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFFA", x"FFF4", x"FFF4", x"FFF5", x"FFF7", x"FFF4",
        x"FFFA", x"FFF5", x"FFF8", x"FFF7", x"FFF8", x"FFF8", x"FFF9", x"FFF9",
        x"FFF7", x"FFFE", x"FFF7", x"FFFC", x"FFFA", x"FFF7", x"FFF7", x"FFF8",
        x"FFF8", x"FFF5", x"FFFD", x"FFF5", x"FFF8", x"FFF9", x"FFF7", x"FFF9",
        x"FFF9", x"FFF9", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF6", x"FFF6", x"FFF4", x"FFF8", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0001", x"FFFF", x"0001",
        x"0001", x"FFFB", x"FFFB", x"FFFC", x"FFFC", x"FFFA", x"FFFF", x"FFFE",
        x"0000", x"0000", x"FFFF", x"0000", x"0000", x"0000", x"FFFF", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFC",
        x"FFFE", x"FFFE", x"FFFE", x"FFFE", x"FFFB", x"FFFC", x"FFFC", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFA", x"FFFC", x"FFFC",
        x"FFFD", x"FFFD", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFF7", x"FFF7",
        x"FFF8", x"FFF8", x"FFF8", x"FFFA", x"FFF6", x"FFF7", x"FFF6", x"FFFB",
        x"FFFC", x"FFFB", x"FFFC", x"FFFB", x"FFFE", x"FFFD", x"FFFE", x"FFFD",
        -- oc=10 (144 values)
        x"FFFC", x"FFFD", x"FFFD", x"FFFC", x"FFFC", x"FFFE", x"FFFD", x"FFFF",
        x"FFFF", x"FFFE", x"FFFF", x"FFFF", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF8", x"FFF9", x"FFF8", x"FFFA", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFFA", x"FFF5", x"FFF4", x"FFF6", x"FFF7", x"FFF4",
        x"FFFB", x"FFF6", x"FFF8", x"FFF7", x"FFF8", x"FFF8", x"FFF9", x"FFF9",
        x"FFF7", x"FFFD", x"FFF7", x"FFFC", x"FFFA", x"FFF6", x"FFF6", x"FFF8",
        x"FFF8", x"FFF4", x"FFFD", x"FFF5", x"FFF8", x"FFF9", x"FFF7", x"FFF9",
        x"FFF9", x"FFF9", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF6", x"FFF6", x"FFF4", x"FFF8", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFD", x"FFFE", x"FFFE", x"FFFC", x"0000", x"FFFF", x"0000",
        x"0000", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"FFFF", x"FFFE",
        x"0000", x"0000", x"FFFF", x"FFFF", x"FFFF", x"FFFF", x"FFFF", x"0000",
        x"FFFF", x"FFFF", x"FFFF", x"FFFC", x"FFFD", x"FFFE", x"FFFC", x"FFFC",
        x"FFFE", x"FFFE", x"FFFE", x"FFFE", x"FFFB", x"FFFC", x"FFFD", x"FFFD",
        x"FFFD", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFFB", x"FFFC", x"FFFC",
        x"FFFD", x"FFFD", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFF7", x"FFF7",
        x"FFF8", x"FFF8", x"FFF7", x"FFFA", x"FFF6", x"FFF7", x"FFF6", x"FFFB",
        x"FFFB", x"FFFB", x"FFFC", x"FFFB", x"FFFD", x"FFFD", x"FFFE", x"FFFD",
        -- oc=11 (144 values)
        x"FFFC", x"FFFD", x"FFFD", x"FFFC", x"FFFC", x"FFFE", x"FFFD", x"FFFF",
        x"FFFF", x"FFFE", x"FFFF", x"FFFF", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF8", x"FFF9", x"FFF8", x"FFFA", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFF9", x"FFF4", x"FFF4", x"FFF5", x"FFF7", x"FFF4",
        x"FFFA", x"FFF5", x"FFF7", x"FFF7", x"FFF8", x"FFF8", x"FFF9", x"FFF9",
        x"FFF7", x"FFFD", x"FFF7", x"FFFC", x"FFFA", x"FFF6", x"FFF6", x"FFF8",
        x"FFF8", x"FFF4", x"FFFD", x"FFF5", x"FFF8", x"FFF9", x"FFF8", x"FFF9",
        x"FFF9", x"FFF9", x"FFF9", x"FFFB", x"FFF8", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF6", x"FFF6", x"FFF4", x"FFF8", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0000", x"FFFF", x"0000",
        x"0000", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"FFFF", x"FFFE",
        x"0000", x"0000", x"FFFF", x"0000", x"0000", x"0000", x"FFFF", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFC", x"FFFD", x"FFFC", x"FFFC",
        x"FFFD", x"FFFD", x"FFFE", x"FFFE", x"FFFB", x"FFFC", x"FFFC", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFB", x"FFFD", x"FFFC",
        x"FFFD", x"FFFE", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFF6", x"FFF7",
        x"FFF8", x"FFF8", x"FFF7", x"FFFA", x"FFF6", x"FFF7", x"FFF6", x"FFFB",
        x"FFFB", x"FFFB", x"FFFC", x"FFFB", x"FFFD", x"FFFD", x"FFFE", x"FFFD",
        -- oc=12 (144 values)
        x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFB", x"FFFE", x"FFFD", x"FFFF",
        x"FFFE", x"FFFE", x"FFFF", x"FFFF", x"FFFE", x"FFFE", x"0001", x"FFFD",
        x"FFFE", x"FFFE", x"FFF8", x"FFF9", x"FFF8", x"FFFA", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFFA", x"FFF5", x"FFF4", x"FFF6", x"FFF7", x"FFF4",
        x"FFFB", x"FFF6", x"FFF8", x"FFF7", x"FFF8", x"FFF8", x"FFF9", x"FFF9",
        x"FFF7", x"FFFD", x"FFF7", x"FFFC", x"FFFA", x"FFF6", x"FFF6", x"FFF8",
        x"FFF8", x"FFF4", x"FFFD", x"FFF5", x"FFF8", x"FFF9", x"FFF7", x"FFF9",
        x"FFF9", x"FFF9", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF6", x"FFF6", x"FFF4", x"FFF8", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0001", x"FFFF", x"0001",
        x"0001", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"0000", x"FFFE",
        x"0000", x"0000", x"FFFF", x"0000", x"0000", x"0000", x"FFFF", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFC",
        x"FFFE", x"FFFE", x"FFFE", x"FFFE", x"FFFB", x"FFFB", x"FFFC", x"FFFC",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFA", x"FFFC", x"FFFC",
        x"FFFD", x"FFFD", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFF6", x"FFF7",
        x"FFF8", x"FFF8", x"FFF7", x"FFFA", x"FFF6", x"FFF7", x"FFF6", x"FFFB",
        x"FFFB", x"FFFB", x"FFFC", x"FFFB", x"FFFD", x"FFFD", x"FFFE", x"FFFD",
        -- oc=13 (144 values)
        x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFB", x"FFFE", x"FFFC", x"FFFF",
        x"FFFE", x"FFFE", x"FFFF", x"FFFF", x"FFFE", x"FFFE", x"0001", x"FFFD",
        x"FFFE", x"FFFF", x"FFF7", x"FFF9", x"FFF8", x"FFFA", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFF9", x"FFF4", x"FFF3", x"FFF5", x"FFF7", x"FFF4",
        x"FFFA", x"FFF5", x"FFF7", x"FFF7", x"FFF8", x"FFF8", x"FFF9", x"FFF9",
        x"FFF7", x"FFFE", x"FFF7", x"FFFC", x"FFFA", x"FFF7", x"FFF6", x"FFF8",
        x"FFF8", x"FFF4", x"FFFD", x"FFF5", x"FFF8", x"FFF9", x"FFF7", x"FFF9",
        x"FFF9", x"FFF9", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF7", x"FFF6", x"FFF4", x"FFF9", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFC", x"0001", x"FFFF", x"0000",
        x"0000", x"FFFC", x"FFFC", x"FFFC", x"FFFD", x"FFFA", x"0000", x"FFFE",
        x"0000", x"0000", x"FFFF", x"0000", x"0000", x"0000", x"FFFF", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFC",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFB", x"FFFB", x"FFFC", x"FFFC",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFA", x"FFFC", x"FFFB",
        x"FFFC", x"FFFD", x"FFFE", x"FFFC", x"FFFD", x"FFFC", x"FFF7", x"FFF7",
        x"FFF8", x"FFF8", x"FFF7", x"FFFB", x"FFF6", x"FFF7", x"FFF6", x"FFFB",
        x"FFFC", x"FFFB", x"FFFC", x"FFFB", x"FFFE", x"FFFD", x"FFFE", x"FFFD",
        -- oc=14 (144 values)
        x"FFFB", x"FFFD", x"FFFD", x"FFFC", x"FFFB", x"FFFE", x"FFFC", x"FFFF",
        x"FFFE", x"FFFE", x"FFFF", x"FFFF", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF8", x"FFF9", x"FFF8", x"FFFA", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFF9", x"FFF4", x"FFF3", x"FFF5", x"FFF7", x"FFF4",
        x"FFFA", x"FFF5", x"FFF7", x"FFF7", x"FFF8", x"FFF8", x"FFFA", x"FFF9",
        x"FFF7", x"FFFE", x"FFF7", x"FFFC", x"FFFA", x"FFF6", x"FFF6", x"FFF7",
        x"FFF8", x"FFF4", x"FFFD", x"FFF5", x"FFF8", x"FFF9", x"FFF7", x"FFF9",
        x"FFF9", x"FFF9", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFFA", x"FFF3",
        x"FFF3", x"FFF6", x"FFF6", x"FFF4", x"FFF8", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFE", x"FFFE", x"FFFE", x"FFFD", x"0001", x"FFFF", x"0001",
        x"0001", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"FFFF", x"FFFE",
        x"0000", x"0000", x"FFFF", x"0000", x"0000", x"0000", x"0000", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFC", x"FFFD", x"FFFC", x"FFFB",
        x"FFFD", x"FFFD", x"FFFE", x"FFFE", x"FFFB", x"FFFC", x"FFFC", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFB", x"FFFD", x"FFFC",
        x"FFFD", x"FFFE", x"FFFF", x"FFFD", x"FFFE", x"FFFD", x"FFF6", x"FFF6",
        x"FFF7", x"FFF7", x"FFF7", x"FFFA", x"FFF5", x"FFF6", x"FFF5", x"FFFB",
        x"FFFC", x"FFFB", x"FFFC", x"FFFB", x"FFFE", x"FFFD", x"FFFE", x"FFFD",
        -- oc=15 (144 values)
        x"FFFB", x"FFFC", x"FFFD", x"FFFB", x"FFFB", x"FFFE", x"FFFC", x"FFFE",
        x"FFFE", x"FFFE", x"FFFF", x"0000", x"FFFF", x"FFFE", x"0001", x"FFFE",
        x"FFFF", x"FFFF", x"FFF7", x"FFF9", x"FFF8", x"FFF9", x"FFFA", x"FFFB",
        x"FFF8", x"FFFB", x"FFF9", x"FFF4", x"FFF3", x"FFF5", x"FFF6", x"FFF3",
        x"FFFA", x"FFF5", x"FFF7", x"FFF6", x"FFF8", x"FFF7", x"FFF9", x"FFF8",
        x"FFF7", x"FFFD", x"FFF6", x"FFFB", x"FFF9", x"FFF6", x"FFF6", x"FFF7",
        x"FFF7", x"FFF4", x"FFFC", x"FFF4", x"FFF7", x"FFF8", x"FFF7", x"FFF9",
        x"FFF8", x"FFF8", x"FFF9", x"FFFB", x"FFF7", x"FFFB", x"FFF9", x"FFF3",
        x"FFF3", x"FFF6", x"FFF6", x"FFF4", x"FFF9", x"FFF6", x"FFF8", x"FFF7",
        x"FFFD", x"FFFD", x"FFFE", x"FFFE", x"FFFC", x"0000", x"FFFF", x"0000",
        x"0000", x"FFFB", x"FFFB", x"FFFC", x"FFFD", x"FFFA", x"FFFF", x"FFFE",
        x"0000", x"0000", x"FFFF", x"0000", x"0000", x"0000", x"0000", x"0000",
        x"0000", x"0000", x"FFFF", x"FFFB", x"FFFC", x"FFFD", x"FFFC", x"FFFB",
        x"FFFD", x"FFFD", x"FFFE", x"FFFD", x"FFFB", x"FFFC", x"FFFC", x"FFFD",
        x"FFFD", x"FFFF", x"FFFB", x"FFFD", x"FFFD", x"FFFA", x"FFFC", x"FFFC",
        x"FFFD", x"FFFD", x"FFFF", x"FFFC", x"FFFE", x"FFFD", x"FFF6", x"FFF7",
        x"FFF8", x"FFF8", x"FFF7", x"FFFA", x"FFF5", x"FFF7", x"FFF6", x"FFFB",
        x"FFFB", x"FFFB", x"FFFB", x"FFFA", x"FFFD", x"FFFC", x"FFFE", x"FFFC"
    );

begin

    process(clk)
    begin
        if rising_edge(clk) then
            if en = '1' then
                dout <= ROM(to_integer(unsigned(addr)));
            end if;
        end if;
    end process;

end architecture rtl;
